import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse } from "yaml";
import { buildPublishedBody } from "../src/publish/publish.js";
import { buildRunMetadataMarker } from "../src/metadata/markers.js";
import { buildMetadataMarker, parseMetadata } from "../src/precheck/metadata.js";

const ROOT = resolve(__dirname, "..", "..");

function expectedVersionSource(version: string): string {
  return `// Generated by scripts/generate-v3-contract.mjs; do not edit.\nexport const ACTION_VERSION: string = ${JSON.stringify(version)};\n`;
}

test("#915: action version appears in the engine line and metadata marker only when stamped", () => {
  const releaseBody = buildPublishedBody({
    markers: "M",
    analysisEngine: "m (openai) — primary route",
    sanitizedMarkdown: "R",
    actionVersion: "v3.1.0",
  });
  assert.ok(releaseBody.includes("_Analysis engine: m (openai) — primary route · pr-reviewer-action v3.1.0_"));

  const devBody = buildPublishedBody({
    markers: "M",
    analysisEngine: "m (openai)",
    sanitizedMarkdown: "R",
    actionVersion: "v3.1.0-dev+abc1234",
  });
  assert.ok(devBody.includes("_Analysis engine: m (openai) · pr-reviewer-action v3.1.0-dev+abc1234_"));

  const unstamped = "M\n_Analysis engine: m (openai)_\n\nR\n";
  assert.equal(buildPublishedBody({
    markers: "M", analysisEngine: "m (openai)", sanitizedMarkdown: "R", actionVersion: "",
  }), unstamped);
  assert.equal(buildPublishedBody({ markers: "M", analysisEngine: "m (openai)", sanitizedMarkdown: "R" }), unstamped);

  const redactedUrl = buildPublishedBody({
    markers: "M",
    analysisEngine: "m@https://user:pass@host/v1 (openai) — primary route",
    sanitizedMarkdown: "R",
    actionVersion: "v3.1.0",
  });
  assert.ok(redactedUrl.includes("_Analysis engine: m (openai) — primary route · pr-reviewer-action v3.1.0_"));
  assert.doesNotMatch(redactedUrl, /user:pass|@host/);
});

test("#915: action_version is appended last and omitted when unstamped", () => {
  assert.equal(
    buildMetadataMarker({ head_sha: "h", base_sha: "b", review_result: "clean", action_version: "v3.1.0" }),
    '<!-- ai-pr-reviewer:{"version":1,"head_sha":"h","base_sha":"b","review_result":"clean","action_version":"v3.1.0"} -->',
  );
  assert.equal(
    buildMetadataMarker({
      head_sha: "h", base_sha: "b", review_result: "clean", tool_budget: 32,
      tool_budget_source: "size-scaled", tool_calls: 30, tool_rounds: 15, max_rounds: 16,
      action_version: "v3.1.0-dev+abc1234",
    }),
    '<!-- ai-pr-reviewer:{"version":1,"head_sha":"h","base_sha":"b","review_result":"clean","tool_budget":32,"tool_budget_source":"size-scaled","tool_calls":30,"tool_rounds":15,"max_rounds":16,"action_version":"v3.1.0-dev+abc1234"} -->',
  );

  const unstamped = '<!-- ai-pr-reviewer:{"version":1,"head_sha":"h","base_sha":"b","review_result":"clean"} -->';
  assert.equal(buildMetadataMarker({ head_sha: "h", base_sha: "b", review_result: "clean", action_version: "" }), unstamped);
  assert.equal(buildMetadataMarker({ head_sha: "h", base_sha: "b", review_result: "clean" }), unstamped);

  assert.equal(
    buildRunMetadataMarker({ headSha: "h", baseSha: "b", reviewResult: "clean", actionVersion: "v3.1.0" }),
    '<!-- ai-pr-reviewer:{"version":1,"head_sha":"h","base_sha":"b","review_result":"clean","action_version":"v3.1.0"} -->',
  );
  assert.equal(buildRunMetadataMarker({ headSha: "h", baseSha: "b", reviewResult: "clean" }), unstamped);

  const parsedStamped = parseMetadata(buildMetadataMarker({
    head_sha: "h", base_sha: "b", review_result: "clean", action_version: "v3.1.0",
  }));
  assert.equal(parsedStamped?.action_version, "v3.1.0");
  const parsedUnstamped = parseMetadata(unstamped);
  assert.ok(parsedUnstamped !== null);
  assert.equal("action_version" in parsedUnstamped, false);
});

test("#915: build generator stamps release/dev versions and fails closed", () => {
  const manifest = JSON.parse(readFileSync(resolve(ROOT, ".release-please-manifest.json"), "utf8")) as Record<string, unknown>;
  const manifestVersion = manifest["."];
  assert.equal(typeof manifestVersion, "string");
  const version = manifestVersion as string;
  const generatedPath = resolve(ROOT, ".v3-generated/version.generated.ts");

  const runGenerator = (overrides: NodeJS.ProcessEnv) => spawnSync(
    process.execPath,
    ["scripts/generate-v3-contract.mjs"],
    { cwd: ROOT, env: { ...process.env, ...overrides }, encoding: "utf8" },
  );
  const assertGenerated = (expectedVersion: string) => {
    assert.equal(readFileSync(generatedPath, "utf8"), expectedVersionSource(expectedVersion));
  };

  try {
    const release = runGenerator({ PR_REVIEWER_BUILD_STAMP: "release" });
    assert.equal(release.status, 0, release.stderr);
    assertGenerated(`v${version}`);

    const dev = runGenerator({
      PR_REVIEWER_BUILD_STAMP: "dev",
      GITHUB_SHA: "0123456789abcdef0123456789abcdef01234567",
    });
    assert.equal(dev.status, 0, dev.stderr);
    assertGenerated(`v${version}-dev+0123456`);

    const unset = runGenerator({ PR_REVIEWER_BUILD_STAMP: "", GITHUB_SHA: "0123456789abcdef0123456789abcdef01234567" });
    assert.equal(unset.status, 0, unset.stderr);
    assertGenerated("");

    const invalid = runGenerator({ PR_REVIEWER_BUILD_STAMP: "staging" });
    assert.notEqual(invalid.status, 0);
    assert.match(invalid.stderr, /PR_REVIEWER_BUILD_STAMP/);

    const malformedSha = runGenerator({
      PR_REVIEWER_BUILD_STAMP: "dev",
      GITHUB_SHA: "not-a-sha",
    });
    assert.notEqual(malformedSha.status, 0);
    assert.match(malformedSha.stderr, /GITHUB_SHA/);

    // #941 review: a pull_request event's GITHUB_SHA is the synthetic merge
    // ref, while the dogfood checkout builds the PR head — the explicit
    // build-source sha must win, or the stamp names a commit never built.
    const mergeRefSha = "80ffd71".padEnd(40, "b"); // event GITHUB_SHA: synthetic merge ref
    const headSha = "1f559e9".padEnd(40, "a"); // what the checkout actually built
    const explicitSource = runGenerator({
      PR_REVIEWER_BUILD_STAMP: "dev",
      GITHUB_SHA: mergeRefSha,
      PR_REVIEWER_BUILD_SHA: headSha,
    });
    assert.equal(explicitSource.status, 0, explicitSource.stderr);
    assertGenerated(`v${version}-dev+1f559e9`);

    const malformedExplicit = runGenerator({
      PR_REVIEWER_BUILD_STAMP: "dev",
      GITHUB_SHA: mergeRefSha,
      PR_REVIEWER_BUILD_SHA: "not-a-sha",
    });
    assert.notEqual(malformedExplicit.status, 0);
    assert.match(malformedExplicit.stderr, /PR_REVIEWER_BUILD_SHA/);

    const missingShaEnv: NodeJS.ProcessEnv = { ...process.env, PR_REVIEWER_BUILD_STAMP: "dev" };
    delete missingShaEnv.GITHUB_SHA;
    const missingSha = spawnSync(process.execPath, ["scripts/generate-v3-contract.mjs"], {
      cwd: ROOT,
      env: missingShaEnv,
      encoding: "utf8",
    });
    assert.notEqual(missingSha.status, 0);
    assert.match(missingSha.stderr, /GITHUB_SHA/);
  } finally {
    const unstamped = runGenerator({ PR_REVIEWER_BUILD_STAMP: "", GITHUB_SHA: "0123456789abcdef0123456789abcdef01234567" });
    assert.equal(unstamped.status, 0, unstamped.stderr);
    assertGenerated("");
  }
});

test("#941 review: dogfood workflows stamp the sha they actually checked out", () => {
  interface WorkflowJob {
    steps?: Array<{ name?: string; uses?: string; with?: { ref?: string }; env?: Record<string, string> }>;
  }
  const stepName = "Build the action bundle";
  const loadJob = (workflow: string): WorkflowJob => {
    const doc = parse(readFileSync(resolve(ROOT, ".github/workflows", workflow), "utf8")) as { jobs?: Record<string, WorkflowJob> };
    const job = Object.values(doc.jobs ?? {}).find((candidate) =>
      (candidate.steps ?? []).some((step) => step.name === stepName));
    assert.ok(job, `${workflow}: no job contains the ${stepName} step`);
    return job;
  };

  for (const workflow of ["ai-pr-review.yaml", "fork-ai-review.yaml"]) {
    const job = loadJob(workflow);
    const buildStep = job.steps?.find((step) => step.name === stepName);
    const stampedSha = buildStep?.env?.PR_REVIEWER_BUILD_SHA;
    assert.ok(stampedSha, `${workflow}: build step sets PR_REVIEWER_BUILD_SHA`);
    const checkoutRefs = (job.steps ?? [])
      .filter((step) => typeof step.uses === "string" && step.uses.startsWith("actions/checkout"))
      .map((step) => step.with?.ref ?? "");
    assert.ok(
      checkoutRefs.includes(stampedSha),
      `${workflow}: PR_REVIEWER_BUILD_SHA (${stampedSha}) must equal a checkout ref of the same job (checkouts: ${checkoutRefs.join(" | ")})`,
    );
  }

  // The same-repo dogfood specifically must stamp the PR head: a
  // pull_request event leaves GITHUB_SHA at the synthetic merge ref, which
  // is not the source the checkout builds (#941 review caught exactly this).
  const sameRepo = loadJob("ai-pr-review.yaml");
  const stampedSha = sameRepo.steps?.find((step) => step.name === stepName)?.env?.PR_REVIEWER_BUILD_SHA;
  // The pull_request branch still stamps the PR head; the #914 comment
  // branch adds the pr-gate-resolved head sha (never the synthetic merge
  // ref or the default-branch sha on a comment run).
  assert.equal(
    stampedSha,
    "${{ github.event_name == 'issue_comment' && (steps.pr-gate.outputs.is_fork == 'true' && github.sha || steps.pr-gate.outputs.head_sha) || github.event.pull_request.head.sha || github.sha }}",
  );
});
