import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { buildPublishedBody } from "../src/publish/publish.js";
import { buildRunMetadataMarker } from "../src/metadata/markers.js";
import { buildMetadataMarker, parseMetadata } from "../src/precheck/metadata.js";

const ROOT = resolve(__dirname, "..", "..");

function expectedVersionSource(version: string): string {
  return `// Generated by scripts/generate-v3-contract.mjs; do not edit.\nexport const ACTION_VERSION: string = ${JSON.stringify(version)};\n`;
}

test("#915: action version appears in the engine line and metadata marker only when stamped", () => {
  const releaseBody = buildPublishedBody({
    markers: "M",
    analysisEngine: "m (openai) — primary route",
    sanitizedMarkdown: "R",
    actionVersion: "v3.1.0",
  });
  assert.ok(releaseBody.includes("_Analysis engine: m (openai) — primary route · pr-reviewer-action v3.1.0_"));

  const devBody = buildPublishedBody({
    markers: "M",
    analysisEngine: "m (openai)",
    sanitizedMarkdown: "R",
    actionVersion: "v3.1.0-dev+abc1234",
  });
  assert.ok(devBody.includes("_Analysis engine: m (openai) · pr-reviewer-action v3.1.0-dev+abc1234_"));

  const unstamped = "M\n_Analysis engine: m (openai)_\n\nR\n";
  assert.equal(buildPublishedBody({
    markers: "M", analysisEngine: "m (openai)", sanitizedMarkdown: "R", actionVersion: "",
  }), unstamped);
  assert.equal(buildPublishedBody({ markers: "M", analysisEngine: "m (openai)", sanitizedMarkdown: "R" }), unstamped);

  const redactedUrl = buildPublishedBody({
    markers: "M",
    analysisEngine: "m@https://user:pass@host/v1 (openai) — primary route",
    sanitizedMarkdown: "R",
    actionVersion: "v3.1.0",
  });
  assert.ok(redactedUrl.includes("_Analysis engine: m (openai) — primary route · pr-reviewer-action v3.1.0_"));
  assert.doesNotMatch(redactedUrl, /user:pass|@host/);
});

test("#915: action_version is appended last and omitted when unstamped", () => {
  assert.equal(
    buildMetadataMarker({ head_sha: "h", base_sha: "b", review_result: "clean", action_version: "v3.1.0" }),
    '<!-- ai-pr-reviewer:{"version":1,"head_sha":"h","base_sha":"b","review_result":"clean","action_version":"v3.1.0"} -->',
  );
  assert.equal(
    buildMetadataMarker({
      head_sha: "h", base_sha: "b", review_result: "clean", tool_budget: 32,
      tool_budget_source: "size-scaled", tool_calls: 30, tool_rounds: 15, max_rounds: 16,
      action_version: "v3.1.0-dev+abc1234",
    }),
    '<!-- ai-pr-reviewer:{"version":1,"head_sha":"h","base_sha":"b","review_result":"clean","tool_budget":32,"tool_budget_source":"size-scaled","tool_calls":30,"tool_rounds":15,"max_rounds":16,"action_version":"v3.1.0-dev+abc1234"} -->',
  );

  const unstamped = '<!-- ai-pr-reviewer:{"version":1,"head_sha":"h","base_sha":"b","review_result":"clean"} -->';
  assert.equal(buildMetadataMarker({ head_sha: "h", base_sha: "b", review_result: "clean", action_version: "" }), unstamped);
  assert.equal(buildMetadataMarker({ head_sha: "h", base_sha: "b", review_result: "clean" }), unstamped);

  assert.equal(
    buildRunMetadataMarker({ headSha: "h", baseSha: "b", reviewResult: "clean", actionVersion: "v3.1.0" }),
    '<!-- ai-pr-reviewer:{"version":1,"head_sha":"h","base_sha":"b","review_result":"clean","action_version":"v3.1.0"} -->',
  );
  assert.equal(buildRunMetadataMarker({ headSha: "h", baseSha: "b", reviewResult: "clean" }), unstamped);

  const parsedStamped = parseMetadata(buildMetadataMarker({
    head_sha: "h", base_sha: "b", review_result: "clean", action_version: "v3.1.0",
  }));
  assert.equal(parsedStamped?.action_version, "v3.1.0");
  const parsedUnstamped = parseMetadata(unstamped);
  assert.ok(parsedUnstamped !== null);
  assert.equal("action_version" in parsedUnstamped, false);
});

test("#915: build generator stamps release/dev versions and fails closed", () => {
  const manifest = JSON.parse(readFileSync(resolve(ROOT, ".release-please-manifest.json"), "utf8")) as Record<string, unknown>;
  const manifestVersion = manifest["."];
  assert.equal(typeof manifestVersion, "string");
  const version = manifestVersion as string;
  const generatedPath = resolve(ROOT, ".v3-generated/version.generated.ts");

  const runGenerator = (overrides: NodeJS.ProcessEnv) => spawnSync(
    process.execPath,
    ["scripts/generate-v3-contract.mjs"],
    { cwd: ROOT, env: { ...process.env, ...overrides }, encoding: "utf8" },
  );
  const assertGenerated = (expectedVersion: string) => {
    assert.equal(readFileSync(generatedPath, "utf8"), expectedVersionSource(expectedVersion));
  };

  try {
    const release = runGenerator({ PR_REVIEWER_BUILD_STAMP: "release" });
    assert.equal(release.status, 0, release.stderr);
    assertGenerated(`v${version}`);

    const dev = runGenerator({
      PR_REVIEWER_BUILD_STAMP: "dev",
      GITHUB_SHA: "0123456789abcdef0123456789abcdef01234567",
    });
    assert.equal(dev.status, 0, dev.stderr);
    assertGenerated(`v${version}-dev+0123456`);

    const unset = runGenerator({ PR_REVIEWER_BUILD_STAMP: "", GITHUB_SHA: "0123456789abcdef0123456789abcdef01234567" });
    assert.equal(unset.status, 0, unset.stderr);
    assertGenerated("");

    const invalid = runGenerator({ PR_REVIEWER_BUILD_STAMP: "staging" });
    assert.notEqual(invalid.status, 0);
    assert.match(invalid.stderr, /PR_REVIEWER_BUILD_STAMP/);

    const malformedSha = runGenerator({
      PR_REVIEWER_BUILD_STAMP: "dev",
      GITHUB_SHA: "not-a-sha",
    });
    assert.notEqual(malformedSha.status, 0);
    assert.match(malformedSha.stderr, /GITHUB_SHA/);

    const missingShaEnv: NodeJS.ProcessEnv = { ...process.env, PR_REVIEWER_BUILD_STAMP: "dev" };
    delete missingShaEnv.GITHUB_SHA;
    const missingSha = spawnSync(process.execPath, ["scripts/generate-v3-contract.mjs"], {
      cwd: ROOT,
      env: missingShaEnv,
      encoding: "utf8",
    });
    assert.notEqual(missingSha.status, 0);
    assert.match(missingSha.stderr, /GITHUB_SHA/);
  } finally {
    const unstamped = runGenerator({ PR_REVIEWER_BUILD_STAMP: "", GITHUB_SHA: "0123456789abcdef0123456789abcdef01234567" });
    assert.equal(unstamped.status, 0, unstamped.stderr);
    assertGenerated("");
  }
});
