import type { ArtifactFinding } from "./artifact.js";
import { capCiOnlyFindings } from "./verdict-policy.js";

/** Split one row produced by the CI gate's escaped Markdown table renderer. */
function splitTableRow(line: string): string[] | null {
  if (!line.startsWith("|") || !line.endsWith("|")) return null;
  const cells: string[] = [];
  let cell = "";
  for (let i = 1; i < line.length - 1; i += 1) {
    const char = line[i]!;
    if (char === "\\" && i + 1 < line.length - 1) {
      const next = line[i + 1]!;
      if (next === "|" || next === "\\" || next === "`") {
        cell += char + next;
        i += 1;
      } else {
        cell += char;
      }
    } else if (char === "|") {
      cells.push(cell.trim());
      cell = "";
    } else {
      cell += char;
    }
  }
  cells.push(cell.trim());
  return cells;
}

function decodeTableCell(cell: string): string {
  return cell
    .replace(/\\([\\|`])/g, "$1")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

/** Read check names from the CI evidence table generated by the gate itself. */
export function parseCiCheckNames(markdown: string | null | undefined): Set<string> {
  const names = new Set<string>();
  if (!markdown) return names;
  let inTable = false;
  for (const line of markdown.split(/\r?\n/)) {
    const cells = splitTableRow(line);
    if (cells === null || cells.length !== 2) continue;
    const name = decodeTableCell(cells[0]!);
    const state = decodeTableCell(cells[1]!);
    if (!inTable) {
      if (name === "Check" && state === "State") inTable = true;
      continue;
    }
    if (name === "---" && state === "---") continue;
    if (name !== "") names.add(name);
  }
  return names;
}

/** Cap check-conclusion-only blocking findings while retaining their origin. */
export function capCiEvidenceFindings(findings: ArtifactFinding[], markdown: string | null | undefined): boolean {
  return capCiOnlyFindings(findings, parseCiCheckNames(markdown));
}
