# shellcheck shell=bash
# Sourced by run_review.sh — user message, model call + fallback, escalation, enforcement, outputs, step summary.
# Verbatim in-order slice of the former monolith (#307); relies on globals/helpers
# set up by the orchestrator. Not executable on its own.

log "Analyzing with $AI_MODEL using $AI_API_FORMAT API format..."

# Build the user message for the final review call, steering it with the
# deterministic classification (pr_kind / risk_flags / must_check). These go
# in the short instruction channel because weaker models weight it far more
# heavily than a section buried mid-corpus. Every value is generated by
# pr_reviewer/classifier.py from file patterns — not copied from PR text — so
# this cannot carry prompt injection from the PR.
build_user_message() {
  local classification_file="${1:-classification.json}"
  local base="Analyze this pull request corpus and return STRICT JSON."
  if [ ! -s "$classification_file" ]; then
    printf '%s' "$base"
    return
  fi
  python3 - "$classification_file" <<'PY'
import json, sys

base = "Analyze this pull request corpus and return STRICT JSON."
try:
    data = json.load(open(sys.argv[1], encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("not an object")
except Exception:
    print(base, end="")
    raise SystemExit(0)

parts = [base]
pr_kind = str(data.get("pr_kind") or "unknown")
parts.append(f"PR kind (deterministic classification): {pr_kind}.")
flags = [str(flag) for flag in (data.get("risk_flags") or []) if flag]
attribution = data.get("risk_flags_with_files") or {}
if flags:
    flag_parts = []
    for flag in flags[:12]:
        files_for_flag = attribution.get(flag) or []
        if files_for_flag:
            file_list = ", ".join(files_for_flag[:5])
            flag_parts.append(f"{flag} (triggered by: {file_list})")
        else:
            flag_parts.append(flag)
    parts.append("Risk flags: " + ", ".join(flag_parts) + ".")
checks = [str(check) for check in (data.get("must_check") or []) if check]
if checks:
    parts.append(
        "Required checks — explicitly address EACH of these in the review "
        "(state what you verified, or why the check does not apply):"
    )
    parts.extend(f"- {check}" for check in checks[:12])
print("\n".join(parts), end="")
PY
}

STREAM_BOOL="false"
if [[ "$(printf '%s' "$AI_STREAM" | tr '[:upper:]' '[:lower:]')" == "true" ]]; then
  STREAM_BOOL="true"
fi

# Carry-forward (#193) is active when this is an incremental review and the
# precheck extracted open findings from the previous review's marker.
CARRY_FORWARD_ACTIVE="false"
if [[ "$EFFECTIVE_SCOPE" == "incremental" ]] && [ -s previous-findings.json ] \
  && [ "$(jq 'length' previous-findings.json 2>/dev/null || echo 0)" -gt 0 ]; then
  CARRY_FORWARD_ACTIVE="true"
fi

# Incremental review against a baseline the previous review flagged as having
# issues. Used for the dirty-baseline escalation trigger.
DIRTY_BASELINE="false"
if [[ "$EFFECTIVE_SCOPE" == "incremental" && "$BASELINE_CLEAN" != "true" ]]; then
  DIRTY_BASELINE="true"
fi

USER_MESSAGE="$(build_user_message classification.json)"
if [[ "$CARRY_FORWARD_ACTIVE" == "true" ]]; then
  USER_MESSAGE="$USER_MESSAGE
The corpus lists Open Findings From the Previous Review. Answer EVERY one: include a finding with the same id and a resolution of resolved, still_open, or not_verifiable_from_delta. Claim resolved only when this delta demonstrably fixes it."
  log "Carry-forward active: $(jq 'length' previous-findings.json) open finding(s) from the previous review"
fi

PRIMARY_OK=0
# native_loop in-conversation verdict (#205): when the tool loop produced its
# own verdict (final turn, full reasoning history preserved), it wrote the
# response to ai-response.primary.json. Parse it and skip the separate review
# call. A parse failure (degraded/oversized/garbled verdict) falls through to
# the standard corpus review below, so this only ever adds capability.
NATIVE_VERDICT_USED=0
if [[ "$(printf '%s' "$TOOL_MODE" | tr '[:upper:]' '[:lower:]')" == "native_loop" ]] \
  && [[ "$(jq -r '.native_loop_verdict_produced // false' tool-harness.json 2>/dev/null)" == "true" ]] \
  && [ -s ai-response.primary.json ]; then
  log "native_loop produced an in-conversation verdict; using it and skipping the separate review call"
  if parse_and_validate ai-response.primary.json; then
    PRIMARY_OK=1
    NATIVE_VERDICT_USED=1
  else
    log "native_loop verdict did not parse; falling back to the standard review call"
  fi
fi

if [ "$NATIVE_VERDICT_USED" -ne 1 ]; then
build_model_request \
  "$AI_API_FORMAT" \
  "$AI_MODEL" \
  "$SYSTEM_PROMPT" \
  "$USER_MESSAGE" \
  review-corpus.truncated.md \
  ai-request.primary.json \
  "$STREAM_BOOL"

PRIMARY_OK=0
ATTEMPT=1
PARSE_FAILS=0
# A response that arrives but won't parse/validate is usually deterministic at
# temperature 0.1 — re-sending the same corpus rarely helps. Cap those attempts
# low and fall through to the fallback model instead of burning the full
# transport-retry budget. Transport/HTTP failures keep the full budget.
PARSE_FAIL_CAP=2
RETRY_DELAY="$AI_PRIMARY_RETRY_DELAY_SEC"
while [ "$ATTEMPT" -le "$AI_PRIMARY_RETRIES" ]; do
  echo "Primary model attempt ${ATTEMPT}/${AI_PRIMARY_RETRIES}: $AI_MODEL @ $AI_BASE_URL ($AI_API_FORMAT)"
  if curl_model "$AI_BASE_URL" "$AI_API_KEY" "$AI_API_FORMAT" ai-request.primary.json ai-response.primary.json "$STREAM_BOOL" "$AI_REQUEST_TIMEOUT_SEC" "$AI_CONNECT_TIMEOUT_SEC"; then
    if { [[ "$STREAM_BOOL" != "true" ]] || reassemble_sse_response ai-response.primary.json "$AI_API_FORMAT"; } && \
      parse_and_validate ai-response.primary.json; then
      PRIMARY_OK=1
      break
    fi

    PARSE_FAILS=$((PARSE_FAILS + 1))
    echo "Primary attempt $ATTEMPT: response received but parse/validate failed (parse failure ${PARSE_FAILS}/${PARSE_FAIL_CAP})" >&2
    if [ -s ai-response.primary.json ]; then
      printf '  response head (first 400 bytes): ' >&2
      head -c 400 ai-response.primary.json >&2 || true
      echo >&2
    fi
    if [ "$PARSE_FAILS" -ge "$PARSE_FAIL_CAP" ]; then
      echo "Reached parse-failure cap; not retrying primary further" >&2
      break
    fi
    ATTEMPT=$((ATTEMPT + 1))
    sleep "$RETRY_DELAY"
  else
    # Transport or HTTP error (curl_model already logged the details/body).
    echo "Primary attempt $ATTEMPT failed (connection/HTTP); waiting ${RETRY_DELAY}s" >&2
    ATTEMPT=$((ATTEMPT + 1))
    sleep "$RETRY_DELAY"
    RETRY_DELAY=$((RETRY_DELAY * 2))
    [ "$RETRY_DELAY" -gt 120 ] && RETRY_DELAY=120
  fi
done
fi  # NATIVE_VERDICT_USED guard

# On total model failure, either fail the step (default, preserves prior
# behaviour) or — when on_model_failure=notice — emit a request_changes notice so
# the publish step posts a visible explanation instead of leaving a red check
# with nothing on the PR. request_changes is the safe default (never auto-approves).
handle_model_failure() {
  local reason="$1"
  error "$reason"
  if [[ "$(printf '%s' "$ON_MODEL_FAILURE" | tr '[:upper:]' '[:lower:]')" != "notice" ]]; then
    exit 1
  fi
  log "on_model_failure=notice: emitting a request_changes notice instead of failing the check"
  ANALYSIS_ENGINE="(model unavailable)"
  REASON="$reason" python3 - > ai-output.json <<'PY'
import json, os
reason = os.environ.get("REASON", "model unavailable")
md = (
    "## AI review could not run\n\n"
    "The configured model endpoint(s) did not return a usable review for this run "
    f"(reason: {reason}).\n\n"
    "This is an automated notice, not a substantive review. Re-run the workflow "
    "once the endpoint is reachable; see the action logs for the underlying error.\n"
)
print(json.dumps({"verdict": "request_changes", "review_markdown": md}))
PY
}

# Append the routing/fallback story to the analysis-engine string, so the
# published "_Analysis engine: …_" line says not just WHICH model produced
# the review but WHY it was chosen: deliberate smart routing, post-review
# escalation, and primary-failure fallback read very differently on cost and
# health. Legacy (routing off) primary success stays unannotated so the
# output is byte-identical for routing-off users.
# Args: $1 = base "model@url (format)" string, $2 = origin: primary|fallback|escalated
# Uses env: REVIEW_ROUTE, ROUTE_REASON, ESCALATION_REASONS
annotate_analysis_engine() {
  local engine="$1" origin="$2"
  case "$origin" in
    fallback)
      engine="$engine — fallback (primary failed)"
      ;;
    escalated)
      engine="$engine — escalated (${ESCALATION_REASONS:-unknown})"
      ;;
    primary)
      case "${REVIEW_ROUTE:-legacy}" in
        primary) engine="$engine — primary route" ;;
        smart) engine="$engine — routed smart (${ROUTE_REASON:-risk match})" ;;
      esac
      ;;
  esac
  printf '%s' "$engine"
}

if [ "$PRIMARY_OK" -eq 1 ]; then
  ANALYSIS_ENGINE="$(annotate_analysis_engine "$AI_MODEL@$AI_BASE_URL ($AI_API_FORMAT)" primary)"
  echo "Primary model succeeded"
else
  TRY_FALLBACK=1
  if [[ -z "$AI_FALLBACK_BASE_URL" || -z "$AI_FALLBACK_MODEL" ]]; then
    # In notice mode handle_model_failure returns; otherwise it exits.
    handle_model_failure "Primary model unavailable and no fallback model configured"
    TRY_FALLBACK=0
  fi

  if [ "$TRY_FALLBACK" -eq 1 ]; then
  echo "Primary model unavailable after retries; trying fallback: $AI_FALLBACK_MODEL @ $AI_FALLBACK_BASE_URL ($AI_FALLBACK_API_FORMAT)" >&2
  head -c 120000 review-corpus.md > review-corpus.fallback.truncated.md

  FALLBACK_STREAM_BOOL="false"
  if [[ "$(printf '%s' "$AI_FALLBACK_STREAM" | tr '[:upper:]' '[:lower:]')" == "true" ]]; then
    FALLBACK_STREAM_BOOL="true"
  fi

  build_model_request \
    "$AI_FALLBACK_API_FORMAT" \
    "$AI_FALLBACK_MODEL" \
    "$SYSTEM_PROMPT" \
    "$USER_MESSAGE" \
    review-corpus.fallback.truncated.md \
    ai-request.fallback.json \
    "$FALLBACK_STREAM_BOOL"

  if curl_model "$AI_FALLBACK_BASE_URL" "$AI_FALLBACK_API_KEY" "$AI_FALLBACK_API_FORMAT" ai-request.fallback.json ai-response.fallback.json "$FALLBACK_STREAM_BOOL" "$AI_FALLBACK_REQUEST_TIMEOUT_SEC" "$AI_FALLBACK_CONNECT_TIMEOUT_SEC" && \
    { [[ "$FALLBACK_STREAM_BOOL" != "true" ]] || reassemble_sse_response ai-response.fallback.json "$AI_FALLBACK_API_FORMAT"; } && \
    parse_and_validate ai-response.fallback.json; then
    ANALYSIS_ENGINE="$(annotate_analysis_engine "$AI_FALLBACK_MODEL@$AI_FALLBACK_BASE_URL ($AI_FALLBACK_API_FORMAT)" fallback)"
    echo "Fallback model succeeded" >&2
  else
    handle_model_failure "Fallback model failed"
  fi
  fi
fi

# ── Escalation (#160) ────────────────────────────────────────────────
# When the primary route produced this review and a configured trigger fires
# (request_changes, unaddressed required checks, low confidence, blocker
# signals), re-run the review on the smart model and publish only that result.
# Escalation requires a configured smart model (ai_smart_model) — it NEVER
# escalates to the fallback. The primary output is kept as ai-output.primary.json
# for debugging. A smart-model failure keeps the primary review.
ESCALATION_REASONS=""
maybe_escalate_review() {
  [[ "$REVIEW_ROUTING_MODE" == "auto" ]] || return 0
  [[ "${REVIEW_ROUTE:-legacy}" == "primary" ]] || return 0
  [[ -n "$SMART_MODEL_RESOLVED" ]] || return 0
  if [[ "$SMART_BASE_URL" == "$AI_BASE_URL" && "$SMART_MODEL" == "$AI_MODEL" ]]; then
    return 0  # nothing distinct to escalate to
  fi
  # Defensive: if the primary failed and the fallback produced this review, and
  # the operator explicitly set ai_smart_model to that same fallback, escalating
  # would just re-call the model that already reviewed this corpus.
  if [[ "${PRIMARY_OK:-0}" -ne 1 && "$SMART_BASE_URL" == "$AI_FALLBACK_BASE_URL" && "$SMART_MODEL" == "$AI_FALLBACK_MODEL" ]]; then
    log "Skipping escalation: the fallback model that produced this review is the smart model"
    return 0
  fi

  # Decide on the RAW primary output, before verdict policy / completeness
  # validation / enforcement mutate it.
  local decision
  decision="$(PYTHONPATH="${SCRIPT_DIR}/.." python3 -c "
from pr_reviewer.escalation import should_escalate
escalate, reasons = should_escalate(
    on_incomplete=('$ESCALATE_ON_INCOMPLETE_REQUIRED_CHECKS' == 'true'),
    on_request_changes=('$ESCALATE_ON_FAST_REQUEST_CHANGES' == 'true'),
    on_low_confidence=('$ESCALATE_ON_FAST_LOW_CONFIDENCE' == 'true'),
    on_blockers=('$ESCALATE_ON_TOOL_OR_EVIDENCE_BLOCKERS' == 'true'),
    on_dirty_baseline=('$ESCALATE_ON_DIRTY_BASELINE' == 'true'),
    on_planning_failure=('$ESCALATE_ON_TOOL_PLANNING_FAILURE' == 'true'),
    dirty_baseline=('$DIRTY_BASELINE' == 'true'),
)
print('yes ' + ','.join(reasons) if escalate else 'no')
" 2>/dev/null || echo no)"
  if [[ "$decision" == "no" || -z "$decision" ]]; then
    log "No escalation triggers fired; keeping the primary review"
    return 0
  fi
  ESCALATION_REASONS="${decision#yes }"
  log "Escalating to smart model $SMART_MODEL ($ESCALATION_REASONS)"

  cp ai-output.json ai-output.primary.json

  local escalated_user
  escalated_user="$USER_MESSAGE
This is an ESCALATED review: a preliminary review was judged insufficient (${ESCALATION_REASONS}). Review thoroughly and address every required check explicitly."

  build_model_request \
    "$SMART_API_FORMAT" \
    "$SMART_MODEL" \
    "$SYSTEM_PROMPT" \
    "$escalated_user" \
    review-corpus.truncated.md \
    ai-request.smart.json \
    "$STREAM_BOOL"

  local attempt smart_ok=0
  for attempt in 1 2; do
    echo "Smart model attempt ${attempt}/2: $SMART_MODEL @ $SMART_BASE_URL ($SMART_API_FORMAT)"
    if curl_model "$SMART_BASE_URL" "$SMART_API_KEY" "$SMART_API_FORMAT" ai-request.smart.json ai-response.smart.json "$STREAM_BOOL" "$AI_REQUEST_TIMEOUT_SEC" "$AI_CONNECT_TIMEOUT_SEC"; then
      if { [[ "$STREAM_BOOL" != "true" ]] || reassemble_sse_response ai-response.smart.json "$SMART_API_FORMAT"; } && \
        parse_and_validate ai-response.smart.json; then
        smart_ok=1
        break
      fi
    fi
    sleep "$AI_PRIMARY_RETRY_DELAY_SEC"
  done

  if [[ "$smart_ok" -eq 1 ]]; then
    REVIEW_ROUTE="escalated"
    ROUTE_REASON="escalated: ${ESCALATION_REASONS}"
    ANALYSIS_ENGINE="$(annotate_analysis_engine "$SMART_MODEL@$SMART_BASE_URL ($SMART_API_FORMAT)" escalated)"
    log "Smart model succeeded; publishing the escalated review"
  else
    # parse_and_validate only rewrites ai-output.json on success, but restore
    # defensively so a partial write can never replace the primary review.
    cp ai-output.primary.json ai-output.json
    ESCALATION_REASONS=""
    log "Smart model failed after escalation; publishing the primary review"
  fi
}
maybe_escalate_review

EVIDENCE_BLOCKER_ENABLED="false"
if [[ "$(printf '%s' "$EVIDENCE_BLOCKER_ENFORCEMENT" | tr '[:upper:]' '[:lower:]')" == "true" ]]; then
  EVIDENCE_BLOCKER_ENABLED="true"
fi

TOOL_FAILURE_ENABLED="false"
if [[ "$(printf '%s' "$TOOL_MODE" | tr '[:upper:]' '[:lower:]')" != "off" ]] && \
  [[ "$(printf '%s' "$TOOL_FAILURE_ENFORCEMENT" | tr '[:upper:]' '[:lower:]')" == "true" ]]; then
  TOOL_FAILURE_ENABLED="true"
fi

apply_all_enforcement_wrapper "$EVIDENCE_BLOCKER_ENABLED" "$TOOL_FAILURE_ENABLED" "$TOOL_MIN_SUCCESSFUL_REQUESTS" "$VERDICT_POLICY" "$VALIDATE_REQUIRED_CHECKS" "$REQUIRED_CHECK_VALIDATION_MODE" "$CARRY_FORWARD_ACTIVE"

echo "analysis_engine=$ANALYSIS_ENGINE" >> "$OUTPUT_FILE"
echo "verdict=$(jq -r '.verdict' ai-output.json)" >> "$OUTPUT_FILE"
echo "verdict_source=$(jq -r '.verdict_source // "model"' ai-output.json)" >> "$OUTPUT_FILE"
echo "required_checks=$(jq -r '.required_checks // "none"' ai-output.json)" >> "$OUTPUT_FILE"
echo "review_route=${REVIEW_ROUTE:-legacy}" >> "$OUTPUT_FILE"
echo "escalation_reason=${ESCALATION_REASONS:-}" >> "$OUTPUT_FILE"

# Use a random heredoc delimiter so model-controlled review text (which can be
# influenced by prompt injection in the PR diff/title/body) cannot terminate the
# multiline output early and inject arbitrary step outputs (e.g. flip the verdict).
RM_DELIM="EOF_$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
{
  echo "review_markdown<<$RM_DELIM"
  jq -r '.review_markdown' ai-output.json
  echo "$RM_DELIM"
} >> "$OUTPUT_FILE"

# Structured findings (normalized JSON array; [] when the model emitted none).
# Same random-delimiter defense — finding messages are model-controlled text.
FD_DELIM="EOF_$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
{
  echo "findings<<$FD_DELIM"
  jq -c '.findings // []' ai-output.json
  echo "$FD_DELIM"
} >> "$OUTPUT_FILE"

# Cross-run evidence memory (#265): the native_loop's gathered-evidence digest,
# carried into the metadata marker by the publish step so the next incremental
# review reuses it. Empty for non-native modes / when no evidence was gathered.
# Same random-delimiter defense — the digest is tool/model-influenced text.
ED_DELIM="EOF_$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
{
  echo "evidence_digest<<$ED_DELIM"
  jq -r '.evidence_digest // ""' tool-harness.json 2>/dev/null || true
  echo "$ED_DELIM"
} >> "$OUTPUT_FILE"

log "Analysis complete. Writing outputs..."
jq -r '.review_markdown' ai-output.json > review-body.md
echo "$(jq -r '.verdict' ai-output.json)" > verdict.txt
echo "$ANALYSIS_ENGINE" > analysis_engine.txt

echo "effective_review_scope=$EFFECTIVE_SCOPE" >> "$OUTPUT_FILE"
if [[ -n "$PREVIOUS_HEAD_SHA" ]]; then
  echo "previous_head_sha=$PREVIOUS_HEAD_SHA" >> "$OUTPUT_FILE"
fi

# Cache hit ratio: per-review prompt-cache effectiveness signal from the
# tool harness (native_loop). Exported as a step output so the publish step
# can include it in the metadata marker for cross-run aggregation (#333).
_chr="-"
if [ -f tool-harness.json ]; then
  _chr="$(jq -r '.usage.cache_hit_ratio // empty' tool-harness.json 2>/dev/null || true)"
fi
[[ -z "$_chr" ]] && _chr="-"
echo "cache_hit_ratio=$_chr" >> "$OUTPUT_FILE"
# Observability: a step-summary table so a user debugging a slow/odd review can
# see the engine, verdict, token usage, truncation, and the active budget
# without digging through raw logs.
write_step_summary() {
  [[ -n "${GITHUB_STEP_SUMMARY:-}" ]] || return 0

  local verdict diff_bytes corpus_bytes prompt_tok comp_tok usage_file
  verdict="$(jq -r '.verdict // "unknown"' ai-output.json 2>/dev/null || echo unknown)"
  diff_bytes="$( [ -f pr.diff ] && wc -c < pr.diff | tr -d ' ' || echo 0 )"
  corpus_bytes="$( [ -f review-corpus.md ] && wc -c < review-corpus.md | tr -d ' ' || echo 0 )"

  usage_file=""
  [ -f ai-response.primary.json ] && usage_file="ai-response.primary.json"
  [[ "$ANALYSIS_ENGINE" == *fallback* || "$ANALYSIS_ENGINE" == "$AI_FALLBACK_MODEL"* ]] && [ -f ai-response.fallback.json ] && usage_file="ai-response.fallback.json"
  [[ "${REVIEW_ROUTE:-}" == "escalated" ]] && [ -f ai-response.smart.json ] && usage_file="ai-response.smart.json"
  prompt_tok="-"; comp_tok="-"
  if [ -n "$usage_file" ]; then
    prompt_tok="$(jq -r '.usage.prompt_tokens // "-"' "$usage_file" 2>/dev/null || echo -)"
    comp_tok="$(jq -r '.usage.completion_tokens // "-"' "$usage_file" 2>/dev/null || echo -)"
  fi

  # Cache hit ratio: from the tool harness (native_loop mode).
  # Falls back to "-" when unavailable (non-native modes or backend doesn't report it).
  local cache_hit_ratio="-"
  if [ -f tool-harness.json ]; then
    cache_hit_ratio="$(jq -r '.usage.cache_hit_ratio // empty' tool-harness.json 2>/dev/null || true)"
  fi
  [[ -z "$cache_hit_ratio" ]] && cache_hit_ratio="-"

  local diff_trunc="no" corpus_trunc="no"
  [ "$diff_bytes" -gt "$MAX_DIFF" ] 2>/dev/null && diff_trunc="yes (cap ${MAX_DIFF})"
  [ "$corpus_bytes" -gt "$MAX_CORPUS" ] 2>/dev/null && corpus_trunc="yes (cap ${MAX_CORPUS})"

  local budget_desc
  if [[ "${MODEL_CONTEXT_TOKENS:-}" =~ ^[0-9]+$ ]]; then
    budget_desc="model_context_tokens=${MODEL_CONTEXT_TOKENS}"
  else
    budget_desc="context_limit_mode=${CONTEXT_LIMIT_MODE:-normal}"
  fi

  local findings_count blockers_count verdict_source
  findings_count="$(jq -r '.findings | length' ai-output.json 2>/dev/null || echo 0)"
  blockers_count="$(jq -r '[.findings[]? | select(.severity == "blocker")] | length' ai-output.json 2>/dev/null || echo 0)"
  verdict_source="$(jq -r '.verdict_source // "model"' ai-output.json 2>/dev/null || echo model)"
  local required_checks_status
  required_checks_status="$(jq -r '.required_checks // "none"' ai-output.json 2>/dev/null || echo none)"

  {
    echo "### AI PR Review"
    echo ""
    echo "| Field | Value |"
    echo "| --- | --- |"
    echo "| Engine | ${ANALYSIS_ENGINE} |"
    echo "| Verdict | ${verdict} (source: ${verdict_source}) |"
    echo "| Findings | ${findings_count} (blockers: ${blockers_count}) |"
    echo "| Required checks | ${required_checks_status} |"
    echo "| Route | ${REVIEW_ROUTE:-legacy} (${ROUTE_REASON:-}) |"
    echo "| Scope | ${EFFECTIVE_SCOPE} |"
    echo "| Budget | ${budget_desc} |"
    echo "| Diff bytes | ${diff_bytes} (truncated: ${diff_trunc}) |"
    echo "| Corpus bytes | ${corpus_bytes} (truncated: ${corpus_trunc}) |"
    echo "| Prompt tokens | ${prompt_tok} |"
    if [[ "$cache_hit_ratio" != "-" ]]; then
      echo "| Cache hit ratio | ${cache_hit_ratio} |"
    fi
    echo "| Completion tokens | ${comp_tok} |"
  } >> "$GITHUB_STEP_SUMMARY" 2>/dev/null || true
}
write_step_summary
