/** #915: the action version stamped into this bundle at build time.
 *
 * Generated by scripts/generate-v3-contract.mjs from
 * .release-please-manifest.json: release builds carry `vX.Y.Z`, dogfood
 * builds of PR source carry `vX.Y.Z-dev+<short sha>`, and unstamped
 * (parity/test/local) builds carry "". Callers must treat "" as absent —
 * engine line and marker stay byte-identical to pre-#915 when unstamped.
 * GITHUB_ACTION_REF cannot serve: it is a SHA for SHA-pinned consumers. */
export { ACTION_VERSION } from "../.v3-generated/version.generated.js";
